<?php

/**
 * @file
 * Provide core functions for Rules filter module.
 */

/**
 * Default path to library folder.
 */
define('RULES_FILTER_LISTJS_PATH', 'sites/all/libraries/listjs/list.min.js');

/**
 * Implements hook_theme().
 */
function rules_filter_theme() {
  return array(
    'rules_filter_rules_form' => array(
      'render element' => 'form',
      'file' => 'theme.inc',
      'template' => 'rules-filter-rules-form',
      'path' => drupal_get_path('module', 'rules_filter') . '/theme',
    ),
  );
}

/**
 * Implements hook_library().
 */
function rules_filter_library() {
  return array(
    'listjs' => array(
      'title' => t('List.js integration'),
      'website' => 'http://listjs.com',
      'version' => '1.1.1',
      'js' => array(
        array('data' => RULES_FILTER_LISTJS_PATH, 'type' => 'file'),
      ),
    ),
  );
}

/**
 * Implements hook_form_alter().
 *
 * Override theme function for 'Rules' and 'Rules components' pages.
 */
function rules_filter_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'rules_admin_reaction_overview' || $form_id == 'rules_admin_components_overview') {

    if (file_exists(RULES_FILTER_LISTJS_PATH)) {

      // Replace #theme function to our custom if List.js plugin installed.
      $form['#theme'] = 'rules_filter_rules_form';
    }
    else {
      // Output warning message if List.js plugin wasn't installed.
      $message = 'List.js plugin has not been installed. <a href="!download-url">
Download</a> compressed version of the plugin and move it into the
sites/all/libraries/listjs directory. See <a href="!module-url">Rules filter
</a> module page for further information.';
      $links = array(
        '!download-url' => 'http://www.listjs.com/overview/download',
        '!module-url' => 'https://www.drupal.org/project/rules_filter',
      );

      drupal_set_message(t($message, $links), 'warning');
    }
  }
}
